version: '3.7'
services:
  jenkins-test:
    container_name: jenkins-test
    volumes:
      - type: bind
        source: C:/Projects/jenkins-pipeline-test/jenkins/jenkins_home
        target: /var/jenkins_home
      - type: bind
        source: C:/Projects
        target: /var/projects
      - type: bind
        source: C:/Projects/jenkins-pipeline-test/jenkins/artifact
        target: /var/artifact
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
  server-test:
    container_name: server-test
    volumes:
      - type: bind
        source: C:/Projects/jenkins-pipeline-test/jenkins/artifact
        target: /var/artifact
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5600:80"